export { default as AttestationRoutes }      from './AttestationRoutes'
export { default as AttestationPassage }     from './AttestationPassage'
export { default as PreparatoryClass }       from './PreparatoryClass'
export { default as Bulletins }              from './Bulletins'
export { default as AttestationLicence }     from './AttestationLicence'
export { default as AttestationDefinitive }  from './AttestationDefinitive'
export { default as AttestationInscription } from './AttestationInscription'
